-- Crea la tabla "prefijos" (codificación por frente/zona/sostenimiento) y la deja
-- administrable desde el panel admin, en vez de ser una lista fija en el código.
-- Corre esto UNA SOLA VEZ en el SQL Editor de Supabase.

create table if not exists prefijos (
  id bigint generated by default as identity primary key,
  frente text not null,
  zona text not null default '',
  sost text not null default '',
  prefijo text not null default '',
  plano text not null default '',
  estado boolean not null default true,
  orden integer,
  created_at timestamptz not null default now()
);

-- Importante: revisa cómo tienes configurado el acceso (RLS) en tus otras tablas
-- (supervisores, capataces, sectores, frentes) y replica lo mismo aquí — esta
-- migración no toca RLS a propósito, para no adivinar tu configuración y terminar
-- bloqueando la tabla sin querer. Si esas tablas tienen RLS con políticas públicas,
-- copia esas mismas políticas para "prefijos"; si no tienen RLS habilitado, no
-- actives RLS aquí tampoco.

-- Migra las 29 filas que hoy viven hardcodeadas en config.js (PREFIJOS_FRENTE),
-- para no perder la codificación existente.
insert into prefijos (frente, zona, sost, prefijo, plano, estado, orden) values
  ('OPB', 'A', 'BD', 'GB/A-', 'CE1072', true, 1),
  ('OPB', 'B', 'BD', 'GB/B-', 'CE1073', true, 2),
  ('OPB', 'C', 'BD', 'GB/C-', 'CE1074', true, 3),
  ('BPN - 32', '', 'Manual', '', '', true, 4),
  ('POZA PC-003', '', 'Manual', '', '', true, 5),
  ('ACCESO POZA PC-003', '', 'Manual', '', '', true, 6),
  ('ZCM08', '', 'ACTIVO', 'A-08/P,A2-08/P,A1-08/P', 'CE1047', true, 7),
  ('ZCM08', '1', 'PASIVO', 'ZCM-08/P', 'CE1046', true, 8),
  ('ZCM08', '2', 'PASIVO', 'ZCM-08/P', 'CE1046', true, 9),
  ('ZCM08', '3', 'PASIVO', 'P3-08/P', 'CE1047', true, 10),
  ('ZCM09', '', 'ACTIVO', 'Z09/A-', 'CE1062', true, 11),
  ('ZCM09', '', 'PASIVO', 'Z09/P-', 'CE1066', true, 12),
  ('VM-08', '', 'Manual', '', '', true, 13),
  ('VM-07', '', 'Manual', '', '', true, 14),
  ('VM-06', '', 'Manual', '', '', true, 15),
  ('VM-05', '', 'Manual', '', '', true, 16),
  ('VM-04', '', 'Manual', '', '', true, 17),
  ('VM-01', '', 'Manual', '', '', true, 18),
  ('VM-16', '', 'Manual', '', '', true, 19),
  ('VM-13', '', 'Manual', '', '', true, 20),
  ('VM-12', '', 'Manual', '', '', true, 21),
  ('PLATAFORMA SALA ELECTRICA', 'Zona 1', 'ACTIVO', 'Z01/A-', 'CE1001', true, 22),
  ('PLATAFORMA SALA ELECTRICA', 'Lateral 1', 'PASIVO', 'L01/P-', 'CE1004', true, 23),
  ('PLATAFORMA SALA ELECTRICA', 'Zona 3', 'PASIVO', 'Z03/P-', 'CE1005', true, 24),
  ('PLATAFORMA SALA ELECTRICA', 'Zona 3', 'ACTIVO', 'Z03/A-', 'CE1002', true, 25),
  ('PLATAFORMA SALA ELECTRICA', 'Zona 2', 'PASIVO', 'Z02/P-', 'CE1005', true, 26),
  ('PLATAFORMA SALA ELECTRICA', 'Zona 2', 'ACTIVO', 'Z02/A-', 'CE1002', true, 27),
  ('PLATAFORMA SALA ELECTRICA', 'Lateral 2', 'PASIVO', 'L02/P-', 'CE1006', true, 28),
  ('PLATAFORMA SALA ELECTRICA', 'Lateral 2', 'ACTIVO', 'L02/A-', 'CE1003', true, 29);
