-- Crea la tabla "redline_supervisores" (supervisores Hegatrux que pueden figurar como
-- responsables de un Redline) y la deja administrable desde el panel admin, en vez de
-- ser una lista fija en index.html (selector "Supervisor Hegatrux que realizó el Redline").
-- Corre esto UNA SOLA VEZ en el SQL Editor de Supabase.
--
-- Nota: esta lista es independiente de "supervisores" (los que llenan el reporte diario) —
-- son personas distintas, por eso es una tabla propia y no una reutilización de esa otra.

create table if not exists redline_supervisores (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  estado boolean not null default true,
  orden integer,
  created_at timestamptz not null default now()
);

-- Importante: revisa cómo tienes configurado el acceso (RLS) en "supervisores" y "capataces"
-- y replica lo mismo aquí — esta migración no toca RLS a propósito, para no adivinar tu
-- configuración y terminar bloqueando la tabla sin querer. Si esas tablas tienen RLS con
-- políticas públicas, copia esas mismas políticas para "redline_supervisores"; si no tienen
-- RLS habilitado, no actives RLS aquí tampoco.

-- Migra los 6 nombres que hoy viven hardcodeados en index.html, para no perder la lista existente.
insert into redline_supervisores (nombre, estado, orden) values
  ('LUIS LOZANO', true, 1),
  ('CAMILO CENTENO', true, 2),
  ('JUAN RODRIGUEZ', true, 3),
  ('JOSE SULLO', true, 4),
  ('CRISTHIAN COLCA', true, 5),
  ('DEREK ARIAS', true, 6);
